### ISSUE TITLE
Problem: "gatsby develop" hängt sich beim Anlegen von Kategorien im Katalog auf, Version: current

### ISSUE THREAD

**Issue by FabioMai** [fabianhinz/learnToCode#21]
"gatsby develop" beim lokalen Ausführen der Applikation via "npm start" hängt sich im Schritt "source and transform nodes" ohne Fehlermeldung auf, wenn neue Ordner (inklusive .md und .png) unterhalb von "Katalog" angelegt werden.

![image](https://user-images.githubusercontent.com/17872073/92726493-f2e06b00-f36d-11ea-9f77-cd59ba909628.png)

## Aufgetretene Probleme
Nach Anlegen neuer Ordner und Unterordner für Lektionen kann die Anwendung nicht gebaut werden.

## Aktuelles Verhalten
Anwendung lässt sich nicht bauen, npm start resultiert aber in keinem Fehler

## Erwartetes Verhalten
Neue Ordnerstruktur wird in Anwendung gerendert und dargestellt.

## Reproduction steps
Klonen von branch content/firstdrafts, npm install, npm start

**Comment by FabioMai** [comment]
Vermutlich fehlt mir noch irgendwas, müssen Kategorien im Katalog zusätzlich noch im Firestorage angelegt werden o.ä.?

Die Lektionen an sich werden dargestellt, wenn ich nur die Lektionen in die bestehenden Untergruppen (z.B. Web) einfüge, aber die Gesamtstruktur mit neuen Kategorien/Unterordnern macht noch Probleme

**Comment by fabianhinz** [comment]
@FabioMai der PR sollte deine Probleme beheben. Hab dich mal als Reviewer eingetragen 🥇
